### ISSUE TITLE
Remove 'specific to OCP' from repo About

### ISSUE THREAD

**Issue by pwright** [rohennes/vale-asciidoc#14]
I was wary about using this repo because it seemed exclusive, but after chatting with @aireilly  it seems you can remove that text from repo 'About' as per https://github.com/pwright/vale-asciidoc

**Comment by aireilly** [comment]
Thanks Paul. We'll get this updated. This repo started as a project for OCP docs, but the scope has been broadened - it should useful be for all CCS AsciiDoc projects.
