### ISSUE TITLE
CheckDollar Symbol rule reports failure for valid code block 

### ISSUE THREAD

**Issue by aireilly** [rohennes/vale-asciidoc#15]
The following codeblock should not be flagged as in error:

```asciidoc
[source,terminal]
----
[core@control-plane-1 ~]$ sudo kubensenter
----
```

**Comment by aireilly** [comment]
or this:

```asciidoc
[source,terminal]
----
NAME          DRIVER               DELETIONPOLICY   AGE
lvms-vg1      topolvm.io           Delete           24h
----
```

**Comment by rohennes** [comment]
Is the second one example output? If it is, the [OCP style guide](https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#formatting) states you should use .Example output before all such instances. IF you do, the rules doesn't trigger.

Anyway, let's track all the false positives in #2. I added these examples to that issue.

I know this rule might be impossible... but I actually find it handy when I forget the $, which is 95% of cases. But it obviously has a lot of potential for false positives.
