### ISSUE TITLE
$ or # in terminal blocks false positives

### ISSUE THREAD

**Issue by rohennes** [rohennes/vale-asciidoc#2]
$ or # symbols are not valid in terminal commands on Windows. Should add an option to exclude flagging of `C:\>`

```
 [source,terminal]
----
C:\> net user <username> 
----
```

**Comment by rohennes** [comment]
Or this:
```

source,terminal]
----
$ oc debug node/<node_name>
----

. Change your root directory to the host:
+
[source,terminal]
----
sh-4.2# chroot /host
----
```

**Comment by rohennes** [comment]
`.Expected output`
Should expected output be incorrect as the style guide does say use .Example output.

**Comment by aireilly** [comment]
> `.Expected output` Should expected output be incorrect as the style guide does say use .Example output.

Yeah I think so

**Comment by rohennes** [comment]
The below code snippet displays the contents of a file. Strictly speaking, it's not a terminal command or output. Perhaps the style guide should say remove the 'terminal' attribute if it's just a snippet of a random file? 

```
The variables can also be read from file using the `--env-file` argument. The following is an example file called `postgresql.env`:

[source,terminal]
----
POSTGRESQL_USER=user
POSTGRESQL_DATABASE=db
POSTGRESQL_PASSWORD=password
----
```

**Comment by rohennes** [comment]
Adding exceptions to the rule for:

- Windows symbol, e.g. `C:\> `
- sshing to node, e.g. `sh-4.2# chroot /host`
- output from the tree command in bash e.g. `.
├── CODEOWNERS
├── README.md
└── scripts
    └── validate-vale-rules.sh`
    
The output of text from files is still being flagged but is TBD if that is an issue or not.

**Comment by rohennes** [comment]
or this:

```asciidoc
[source,terminal]
----
NAME          DRIVER               DELETIONPOLICY   AGE
lvms-vg1      topolvm.io           Delete           24h
----
```

edit: this is OK and as designed, it should have `.Example output` title. 

`CheckDollarSymbolInTerminalBlock` rule is unclear IMO. There should be one rule for the `$` / `#` cmd prompt, and another for example outputs.

**Comment by rohennes** [comment]
The following codeblock should not be flagged as in error:

```asciidoc
[source,terminal]
----
[core@control-plane-1 ~]$ sudo kubensenter
----
```

**Comment by rohennes** [comment]
> ![image](https://user-images.githubusercontent.com/74046732/217323105-281f9151-afd6-406e-ac4a-dd392aa1a78e.png)
> 
> This is valid and should be allowed:
> 
> ```
> [source,yaml]
> ----
> include::yaml/boundary-clock-ptp-config.yaml[]
> ----
> ```

Looks like an issue related to nesting rather than false positive for a cmd prompt in a code block

**Comment by rohennes** [comment]
https://github.com/rohennes/vale-asciidoc/commit/a3b39172ab8e84f8d05948cf404918e8bbbd693c fixes all examples in this issue.

I think the only remaining issue is to separate .Example output and cmd prompt rules. Will create a separate issue for that. But also there is the wrinkle that some file outputs use the terminal attribute, when strictly speaking it's not terminal output. So i think there is user error there or something to be sorted in the SSG.
