### ISSUE TITLE
Rewrite to Minimize Error Descriptions

### ISSUE THREAD

**Issue by ktothill** [rohennes/vale-asciidoc#5]
Some of the current error descriptions are posed as questions to the user. By rewriting them in an active, minimalistic style, errors should be easier for users to action.

Example Content:
> "Does the terminal code block contain a $ or # at the beginning of the line? For example output, prepend the code block for the output with the title '.Example output'."

Example Rewrite:
No $ or # detected in code block. Prepend code block with $ or #.

**Comment by aireilly** [comment]
related: https://github.com/rohennes/vale-asciidoc/issues/35
